FROM ghcr.io/bruin-data/bruin:v0.11.493

WORKDIR /workspace

COPY pyproject.toml .

# in order to prevent permission issue we force uc sync during the docker build,
# do the folder like .venv or others can be created
RUN /home/bruin/.bruin/uv sync
