name: Terraform Apply

on:
  workflow_dispatch:        # manual trigger only

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}" >> .env
          echo "GCS_BUCKET=${{ vars.GCS_BUCKET }}" >> .env
          echo "GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS" >> .env
          echo "TF_VAR_project_id=${{ vars.GCP_PROJECT_ID }}" >> .env
          echo "TF_VAR_region=${{ vars.TF_REGION }}" >> .env
          echo "TF_VAR_bucket=${{ vars.TF_BUCKET }}" >> .env

      - name: Start Terraform container
        run: docker compose up -d terraform

      - name: Terraform init
        run: docker exec terraform terraform init

      - name: Terraform apply
        run: docker exec terraform terraform apply -auto-approve

      - name: Tear down
        if: always()
        run: docker compose down
